nome = input('Digite seu nome:').strip()
print('Seu nome maiúsculo é:')
print(nome.upper())
print('A quantidade de letras no seu nome é:')
print(len(nome)-nome.count(' '))
print('Seu nome em minúsculo é:')
print(nome.lower())
print('Seu primeiro nome tem essa quantidade de letras:')
print(nome.find(' '))